const SUPABASE_URL = 'https://gonldcbklguwjhekjhff.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbmxkY2JrbGd1d2poZWtqaGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NTg3MjIsImV4cCI6MjA4ODAzNDcyMn0.UEKkRK4o-XDfA-8YwYf_syaGyiaepTjFNfruBvB1uFk';
