name: dar_alamirat_requests
description: "an app for dar alamirat requests"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.12.2
  lucide_icons: ^0.257.0
  google_fonts: ^8.0.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  go_router: ^17.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  pdf: ^3.10.8
  printing: ^5.11.1
  hijri: ^3.0.0
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  excel: ^4.0.5
  path_provider: ^2.1.2
  share_plus: ^10.1.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/lang/
    - assets/google_fonts/Cairo-Regular.ttf
    - assets/google_fonts/Cairo-Bold.ttf
    - shorebird.yaml
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/google_fonts/Cairo-Regular.ttf
        - asset: assets/google_fonts/Cairo-Bold.ttf
          weight: 700
    - family: NotoKufiArabic
      fonts:
        - asset: assets/google_fonts/NotoKufiArabic-Regular.ttf
        - asset: assets/google_fonts/NotoKufiArabic-Bold.ttf
          weight: 700


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splach_screen.jpg"
  android_12:
    image: "assets/images/splach_screen.jpg"
  android: true
  ios: true
  web: false
